# Generated by Django 4.2.16 on 2026-04-16 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0015_alter_attendance_id_alter_notice_id_and_more'),
    ]

    operations = [
    ]
