from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('', views.home_view, name='home'),
    path('adminclick', views.adminclick_view, name='adminclick'),
    path('teacherclick', views.teacherclick_view, name='teacherclick'),
    path('studentclick', views.studentclick_view, name='studentclick'),
    path('adminsignup', views.admin_signup_view, name='adminsignup'),
    path('teachersignup', views.teacher_signup_view, name='teachersignup'),
    path('studentsignup', views.student_signup_view, name='studentsignup'),
    path('adminlogin', auth_views.LoginView.as_view(template_name='school/adminlogin.html', redirect_authenticated_user=True), name='adminlogin'),
    path('teacherlogin', auth_views.LoginView.as_view(template_name='school/teacherlogin.html', redirect_authenticated_user=True), name='teacherlogin'),
    path('studentlogin', auth_views.LoginView.as_view(template_name='school/studentlogin.html', redirect_authenticated_user=True), name='studentlogin'),
    path('logout', auth_views.LogoutView.as_view(next_page='home'), name='logout'),
    path('afterlogin', views.afterlogin_view, name='afterlogin'),
    path('admin-dashboard', views.admin_dashboard_view, name='admin-dashboard'),
    path('teacher-dashboard', views.teacher_dashboard_view, name='teacher-dashboard'),
    path('student-dashboard', views.student_dashboard_view, name='student-dashboard'),
    path('admin-teacher', views.admin_teacher_view, name='admin-teacher'),
    path('admin-add-teacher', views.admin_add_teacher_view, name='admin-add-teacher'),
    path('admin-view-teacher', views.admin_view_teacher_view, name='admin-view-teacher'),
    path('admin-approve-teacher', views.admin_approve_teacher_view, name='admin-approve-teacher'),
    path('approve-teacher/<int:pk>', views.approve_teacher_view, name='approve-teacher'),
    path('delete-teacher/<int:pk>', views.delete_teacher_view, name='delete-teacher'),
    path('delete-teacher-from-school/<int:pk>', views.delete_teacher_from_school_view, name='delete-teacher-from-school'),
    path('update-teacher/<int:pk>', views.update_teacher_view, name='update-teacher'),
    path('admin-view-teacher-salary', views.admin_view_teacher_salary_view, name='admin-view-teacher-salary'),
    path('admin-student', views.admin_student_view, name='admin-student'),
    path('admin-add-student', views.admin_add_student_view, name='admin-add-student'),
    path('admin-view-student', views.admin_view_student_view, name='admin-view-student'),
    path('admin-approve-student', views.admin_approve_student_view, name='admin-approve-student'),
    path('approve-student/<int:pk>', views.approve_student_view, name='approve-student'),
    path('delete-student/<int:pk>', views.delete_student_view, name='delete-student'),
    path('delete-student-from-school/<int:pk>', views.delete_student_from_school_view, name='delete-student-from-school'),
    path('update-student/<int:pk>', views.update_student_view, name='update-student'),
    path('admin-view-student-fee', views.admin_view_student_fee_view, name='admin-view-student-fee'),
    path('admin-attendance', views.admin_attendance_view, name='admin-attendance'),
    path('admin-take-attendance/<str:cl>', views.admin_take_attendance_view, name='admin-take-attendance'),
    path('admin-view-attendance/<str:cl>', views.admin_view_attendance_view, name='admin-view-attendance'),
    path('admin-fee', views.admin_fee_view, name='admin-fee'),
    path('admin-view-fee/<str:cl>', views.admin_view_fee_view, name='admin-view-fee'),
    path('admin-notice', views.admin_notice_view, name='admin-notice'),
    path('teacher-attendance', views.teacher_attendance_view, name='teacher-attendance'),
    path('teacher-take-attendance/<str:cl>', views.teacher_take_attendance_view, name='teacher-take-attendance'),
    path('teacher-view-attendance/<str:cl>', views.teacher_view_attendance_view, name='teacher-view-attendance'),
    path('teacher-notice', views.teacher_notice_view, name='teacher-notice'),
    path('student-attendance', views.student_attendance_view, name='student-attendance'),
    path('aboutus', views.aboutus_view, name='aboutus'),
    path('contactus', views.contactus_view, name='contactus'),
]
